include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    prefer_const_constructors_in_immutables: true

analyzer:
  plugins:
    - custom_lint
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
